---
# Requires CentOS

- name: Role Facts
  set_fact:
    sock_port: 4243

#- name: Disable listener for Jenkins Docker Plugin
#  lineinfile:
#    path: /etc/docker/daemon.json
#    regexp: '^\s+\"hosts\"\:\s+\["tcp://0\.0\.0\.0:{{ sock_port }}",\s+\"unix:///var/run/docker.sock\"\]'
#    state: absent
#  #notify: Restart Docker

- name: Install RPM
  yum:
    name: "{{ item }}"
  with_items:
    - git
  become: true

- name: Ugrade All Packages
  yum:
    name: '*'
    state: latest

- name: Install Latest docker-compose
  shell: |
    curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  args:
    warn: no
  become: true

- name: Copy "{{ compose_dir }}"
  copy:
    src: "{{ compose_dir }}"
    dest: "{{ compose_home }}"
    owner: root
    group: root
    mode: 0644

#- name: sync source from local directory
#  synchronize:
#    src: "{{ compose_dir }}"
#    dest: "{{ compose_home }}"
#    recursive: true

- name: Run docker-compose.yml
  shell: docker-compose up -d
  args:
    chdir: "{{ compose_home }}/{{ compose_dir }}"
