version: '3.0'

services:

  gogs:
    restart: unless-stopped
    image: gogs/gogs:0.11.29
    volumes:
      - gogs-vol:/data
    ports:
      - "10022:22"
      - "3000:3000"
    depends_on:
      - mariadb

  mariadb:
    restart: unless-stopped
    image: mariadb:10.3.2
    volumes:
      - mariadb-vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"

  jenkins:
    restart: unless-stopped
    #image: jenkins:2.60.3
    build: ./jenkins
    volumes:
      - jenkins-vol:/var/jenkins_home
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    ports:
      - "8080:8080"
      - "50000:50000"

  nexus:
    restart: unless-stopped
    image: sonatype/nexus3:3.6.0
    volumes:
      - nexus-vol:/nexus-data
    ports:
      - "8181:8081"
      - "8182:8082"
      - "8183:8083"

  #artifactory:
  #  restart: unless-stopped
  #  image: docker.bintray.io/jfrog/artifactory-oss
  #  volumes:
  #    - artifactory-vol:/var/opt/jfrog/artifactory
  #  ports:
  #    - "8081:8081"

  cadvisor:
    restart: unless-stopped
    image: google/cadvisor:v0.27.1
    privileged: true
    volumes:
      - /:/rootfs:ro 
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /cgroup:/cgroup:ro
    ports:
      - "8089:8080"

volumes:
  jenkins-vol:
  mariadb-vol:
  gogs-vol:
  nexus-vol:
